spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: SEU_CLIENT_ID_GOOGLE
            client-secret: SEU_CLIENT_SECRET_GOOGLE
            scope:
              - email
              - profile

          facebook:
            client-id: SEU_CLIENT_ID_FACEBOOK
            client-secret: SEU_CLIENT_SECRET_FACEBOOK
            scope:
              - email
              - public_profile

          twitter:
            client-id: SEU_CLIENT_ID_TWITTER
            client-secret: SEU_CLIENT_SECRET_TWITTER
            scope:
              - tweet.read
              - users.read
              - offline.access
              - email

        provider:
          facebook:
            authorization-uri: https://www.facebook.com/dialog/oauth
            token-uri: https://graph.facebook.com/oauth/access_token
            user-info-uri: https://graph.facebook.com/me?fields=id,name,email

          twitter:
            authorization-uri: https://twitter.com/i/oauth2/authorize
            token-uri: https://api.twitter.com/2/oauth2/token
            user-info-uri: https://api.twitter.com/2/users/me
